PLUGIN_NAME=		freeradius-min
PLUGIN_VERSION=		1.0.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		RADIUS Authentication, Authorization and Accounting Server
PLUGIN_DEPENDS=		freeradius3
PLUGIN_MAINTAINER=	rob.hamblet@gmail.com

.include "../../Mk/plugins.mk"
